"""add policy_acknowledged_at to staff

Revision ID: 0e44c1f96b2a
Revises: 6f99699f03d7
Create Date: 2026-06-24 16:50:25.019081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e44c1f96b2a'
down_revision: Union[str, Sequence[str], None] = '6f99699f03d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_allocations', 'allocated_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('staff', sa.Column('policy_acknowledged_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'policy_acknowledged_at')
    op.alter_column('asset_allocations', 'allocated_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
