"""Drop column job title

Revision ID: 62e865bdeb76
Revises: aa0d39cbe600
Create Date: 2026-06-08 09:45:06.986136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '62e865bdeb76'
down_revision: Union[str, Sequence[str], None] = 'aa0d39cbe600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'job_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('job_title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
