"""removed title

Revision ID: 82ba85611e1d
Revises: ce8dc680c96d
Create Date: 2026-06-04 11:20:54.988034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82ba85611e1d'
down_revision: Union[str, Sequence[str], None] = 'ce8dc680c96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
