"""Add session_id fk to audit_logs

Revision ID: ce8dc680c96d
Revises: 7fbaba2fc58b
Create Date: 2026-06-04 10:18:21.103299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ce8dc680c96d'
down_revision: Union[str, Sequence[str], None] = '7fbaba2fc58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('session_id', sa.Integer(), nullable=True))
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.create_foreign_key(None, 'audit_logs', 'sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.drop_column('audit_logs', 'session_id')
    # ### end Alembic commands ###
