"""ict_personnel_nullable_specialization

Revision ID: eee8a026b3d1
Revises: 6eeea54071b1
Create Date: 2026-06-12 11:40:08.390368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eee8a026b3d1'
down_revision: Union[str, Sequence[str], None] = '6eeea54071b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ict_personnel', 'specialization',
               existing_type=postgresql.ENUM('hardware', 'networking', 'software_and_systems', 'security', 'other', name='specialization'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ict_personnel', 'specialization',
               existing_type=postgresql.ENUM('hardware', 'networking', 'software_and_systems', 'security', 'other', name='specialization'),
               nullable=False)
    # ### end Alembic commands ###
